/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello_World_JNI_CustomJNICpp */

#ifndef _Included_Hello_World_JNI_CustomJNICpp
#define _Included_Hello_World_JNI_CustomJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello_World_JNI_CustomJNICpp
 * Method:    sayHello
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Hello_World_JNI_CustomJNICpp_sayHello
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
